[filter]
ignore_process_name = ["^bash$", "^sshd$"]
target_user = "myname"

[output]
format = "json"              # or "msgpack"
path = "/var/log/fuzmon/"
compress = true

[monitor]
interval_sec = 60
record_cpu_time_percent_threshold = 0.0
stacktrace_cpu_time_percent_threshold = 0.0
