# Recommended settings when running fuzmon as a daemon

[output]
format = "msgpack"
path = "/var/log/fuzmon/"
compress = true

[monitor]
interval_sec = 60
record_cpu_time_percent_threshold = 0.0
stacktrace_cpu_time_percent_threshold = 1.0
