name: CI

on:
  pull_request:
    push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/ci.yml') }}
          restore-keys: ${{ runner.os }}-apt-
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y gcc libunwind-dev libfontconfig-dev
      - name: Allow ptrace
        run: sudo sysctl -w kernel.yama.ptrace_scope=0
      - name: Build
        run: cargo build --verbose
      - name: Run basic check
        run: |
          timeout -k 3 ./target/debug/fuzmon > output.txt 2>&1 || true
          test -s output.txt
      - name: Test
        run: cargo test --verbose -- --nocapture
